
  version: '3.8'

  services:
    fastapi:
      build: .
      ports:
        - "8000:8000"
      volumes:
        - .:/app
      environment:
        - PYTHONUNBUFFERED=1
      env_file:
        - .env
      networks:
        - fastapi_network

  networks:
    fastapi_network:
      driver: bridge
    